server:
  port: 8080  # Gateway는 8080 포트

spring:
  application:
    name: gateway
  data:
    redis:
      host: my-cache-server
      port: 6379
      timeout: 2000
      jedis:
        pool:
          max-idle: 10 # 연결 풀에서 유지될 수 있는 최대 유휴 연결 수
          min-idle: 2 # 연결 풀에서 유지될 최소 유휴 연결 수
          max-active: 10 # 연결 풀에서 동시에 활성화된 최대 연결 수
          max-wait: 2000 # 연결을 얻을 때 대기할 수 있는 최대 시간

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-server:8080 # 실제 경로
          predicates:
            - Path=/api/user-server/** # gateway 인입 경로 지정
          filters:
            - StripPrefix=2 # 실제 경로로 요청시 prefix 제거

        - id: board-service
          uri: http://board-server:8080
          predicates:
            - Path=/api/board-server/**
          filters:
            - StripPrefix=2

        - id: point-service
          uri: http://point-server:8080
          predicates:
            - Path=/api/point-server/**
          filters:
            - StripPrefix=2

# jwt
jwt:
  secret: 3541c154-0a34-4478-aecf-bd0b3badc63c
  expirationInMs: 1800000

# logging
logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace
      springframework:
        security: debug
        web: debug

# swagger
springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: user-service
        url: /api/user-server/v3/api-docs
      - name: board-service
        url: /api/board-server/v3/api-docs
      - name: point-service
        url: /api/point-server/v3/api-docs