server:
  port: 8080  # Gateway는 8080 포트

spring:
  application:
    name: gateway
  data:
    redis:
      host: my-cache-server
      port: 6379
      timeout: 2000
      jedis:
        pool:
          max-idle: 10 # 연결 풀에서 유지될 수 있는 최대 유휴 연결 수
          min-idle: 2 # 연결 풀에서 유지될 최소 유휴 연결 수
          max-active: 10 # 연결 풀에서 동시에 활성화된 최대 연결 수
          max-wait: 2000 # 연결을 얻을 때 대기할 수 있는 최대 시간

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-server:8080  # 컨테이너 이름 사용
          predicates:
            - Path=/api/users/**  # 요청 경로에 /api/users/**가 포함될 경우
          filters:
            - StripPrefix=2  # /api/users를 제거하고 실제 user-server의 경로로 전달

        - id: board-service
          uri: http://board-server:8080  # 컨테이너 이름 사용
          predicates:
            - Path=/api/boards/**  # 요청 경로에 /api/boards/**가 포함될 경우
          filters:
            - StripPrefix=2  # /api/boards를 제거하고 실제 board-server의 경로로 전달

      default-filters:
        - name: RequestRateLimiter # 유저당 호출 제한
        - name: AddRequestHeader
          args:
            name: X-Gateway
            value: true

# jwt
jwt:
  secret: 3541c154-0a34-4478-aecf-bd0b3badc63c
  expirationInMs: 86400000

# logging
logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace

# swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true